spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/movie?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
mybatis:
  type-aliases-package: com.xiao.amovie.entity
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql